# A generic, single database configuration.
[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./dev.db

timeline = false

dialect_opts =

[post_write_hooks]
# Comma-separated list of hooks